Add getSortDescFirst to sorting column api
TanStack/table pull request #3956
Opened 2022-05-23 20:03 UTC by mr-bjerre

Add getSortDescFirst to resolve the discussion in #3944

2022-05-23 20:07 UTC, mr-bjerre commented
I'd say `column.getNextSortingOrder()` would be even better than the more low level method `column.getSortDescFirst()`. The only use case for `column.getSortDescFirst()` is to determine `column.getNextSortingOrder()` AFAIK.

But `toggleSorting` seems pretty complex so I'm not sure how to make `getNextSortingOrder`.

Why this in the first place? You might want to hint the next sorting order on mouse hover. E.g. see https://tailwindui.com/components/application-ui/lists/tables#component-7b5a46e74e475708d966ca31716f1771

2022-05-23 21:09 UTC, tannerlinsley requested changes
Any way we can have the toggler logic use this new function?

2022-05-23 21:09 UTC, tannerlinsley commented on packages/table-core/src/features/Sorting.ts
> +          return 'none'
Let’s make this a false, that way we can check it for truthiness much easier.

2022-05-23 21:12 UTC, mr-bjerre commented
Yeah I was going in that direction first but then my head started spinning in the toggler logic 😂

I'll revisit again tomorrow (Copenhagen time here so done for the night)

2022-05-24 07:41 UTC, mr-bjerre commented on packages/table-core/src/features/Sorting.ts
> +        const nextSortingOrder = column.getNextSortingOrder()
@tannerlinsley I first put this line inside `instance.setSorting` but then the react sorting example broke when `sortAction` became `toggle`. It wasn't clear to me exactly why but I assume some state not being in sync on rerender.

2022-05-24 07:41 UTC, mr-bjerre commented
Updated the PR - let me know if it needs more attention

2022-05-27 06:16 UTC, mr-bjerre commented
Maybe I should change the method so we return both sortAction and the next sortDirection (if any) instead?

2022-05-29 20:18 UTC, tannerlinsley approved these changes

2022-05-29 20:20 UTC, merged