Fix svelte adapter issues
TanStack/table pull request #3980
Opened 2022-05-31 05:20 UTC by Mokshit06

This PR fixes the following issues in the svelte adapter:
- make the `Placeholder` component work on both server and client
- custom components (cell/footer) work with hydration
- detect svelte components in hmr env and handle them

2022-05-31 05:21 UTC, Mokshit06 commented
I think I created this pr from alpha branch, should I close this one and create another one from beta?

2022-05-31 06:02 UTC, KevinVandy commented
> I think I created this pr from alpha branch, should I close this one and create another one from beta?

Pretty sure its fine since alpha -> beta when its ready for new beta release, but will hold off merging till @tannerlinsley confirms.

2022-05-31 13:00 UTC, tannerlinsley requested changes

2022-05-31 13:05 UTC, Mokshit06 commented on packages/svelte-table/src/placeholder.ts
> +  ($$result, $$props, $$bindings, slots) => {
I think we can change to what the svelte language server shows. I'll add that commit

2022-06-03 18:43 UTC, tannerlinsley commented
Should be fine.

2022-06-03 18:43 UTC, merged