fix(types): correctly set type for `AccessorKeyColumnDef#accessorKey`
TanStack/table pull request #4513
Opened 2022-11-11 08:12 UTC by Dev-CasperTheGhost

**This PR includes:**

Sets the correct type for `AccessorKeyColumnDef#accessorKey`. Currently with out this PR it doesn't give the correct auto complete, with this fix it does.

2022-11-15 02:32 UTC, KevinVandy commented
@Dev-CasperTheGhost I just tested this and your PR does fix the auto-complete when not using the columnHelper function. However there are now merge conflicts with it after a big type refactor. If you remake this by tomorrow, I'll review again.

2022-11-15 02:32 UTC, KevinVandy requested changes
merge conflicts

2022-11-15 06:01 UTC, Dev-CasperTheGhost commented
@KevinVandy, merge conflicts are fixed :)

2022-11-16 00:21 UTC, KevinVandy approved these changes

2022-11-16 00:22 UTC, merged