fix: do not crash when sorting state has non existing columns
TanStack/table pull request #4665
Opened 2023-01-18 07:56 UTC by targos

We have very dynamic columns in our project (they can be added, sorted, then removed based on the data manipulated by the user).
It would be unnecessarily complicated and error prone to have to reset the sorting everywhere we make changes that may affect the existing columns.

2023-01-23 00:40 UTC, KevinVandy requested changes

2023-01-23 00:40 UTC, KevinVandy commented on packages/table-core/src/utils/getSortedRowModel.ts
> +          table._getAllFlatColumnsById()[sort.id] &&
Think we can just add some optional chaining here

2023-01-26 03:28 UTC, KevinVandy commented
Closing this in favor of #4678

2023-01-26 03:28 UTC, closed without merging

2023-01-26 07:39 UTC, targos commented
Thanks, I like what was done in #4678