set row[accessorString] as default
TanStack/table pull request #82
Opened 2017-02-15 22:34 UTC by avnunn

I'm having an issue where the accessor has a dot in it.

For example I have this dataset:
```json
{
  "foo.bar": "foobar"
}
```

Using the accessor "foo.bar" will be translated to ["foo", "bar"] array path.
In this scenario I just want ["foo.bar"] to be the array path.

This pull is not ideal -- what if I have a dataset such as:
```json
{
  "foo.bar": {
    "foo.baz": 1
   }
}
```

It would be ideal if I could supply an array as the accessor which isn't flattened.

For reference, libraries like lodash support this via their 'get' function.
https://lodash.com/docs/4.17.4#get

For now I will just supply a custom render function for reach column that properly accesses the data I want or just my fork.

2017-02-15 22:45 UTC, tannerlinsley commented
The only strange edge case that could exist if we accept this is something like:
```
const columnDef = { accessor: 'my.path' }
const rowSample = { 'my.path': 10, my: { path: undefined }}
// The value would access to `10`, not `undefined`
```
Is this simply a liability the user takes on if their data is modeled that way?

2017-02-15 22:46 UTC, tannerlinsley approved these changes

2017-02-15 22:49 UTC, tannerlinsley commented
Actually, looking at this again, that could prove to be troublesome for your specific example.

2017-02-15 22:49 UTC, tannerlinsley requested changes
Not sure yet on the changes required, but I think we could improve.

2017-02-15 22:51 UTC, avnunn commented
That is correct, there isn't a clear way forward since it is ambiguous.

This pull is mostly meant to highlight the issue and gather suggestions for improvement.

Ideally I think we could supply an array for the accessor field.
If an array is passed in then all it needs is to be flattened.

2017-02-15 22:52 UTC, avnunn commented
```
const columnDef = { accessor: ['my.path'] }
const rowSample = { 'my.path': 10, my: { path: undefined }}
// The value would access to `10`, not `undefined`
```
```
const columnDef = { accessor: ['my', 'path'] }
const rowSample = { 'my.path': 10, my: { path: undefined }}
// The value would access to `undefined`, not `10`
```

2017-02-15 22:57 UTC, tannerlinsley commented
This would effectively kill accessors for anyone utilizing recursive flattening:
```javascript
const data = { pre: { fix: { foo: 'bar' } } }
const prefix = 'pre.fix'
{
  accessor: [prefix, 'foo']
}
```

It feels like any schema with keys that contain `.`'s is very uncommon.  I just want to make sure we're not optimizing for an edge case that should ultimately be handled by the user to make sure they are complying with a deterministic api.

2017-02-15 23:03 UTC, tannerlinsley commented
Could this also be solved by using lodash itself?

```javascript
const getWithArray = path => row => _.get(row, path)

{
  accessor: getWithArray(['foo.bar', 'foo.baz'])
}
```

2017-02-15 23:33 UTC, avnunn commented
That should work and coincidentally how I am currently solving the issue.
There are a few ways to solve this issue on the client's end.

Keys that contain dots are probably uncommon, if this is something that isn't supported perhaps some documentation is in order to let users know the work-around.
For example I didn't even know that my accessor string was being interpreted to an array. Wasn't till I loaded up the code to see why my table was blank.

Unfortunately there isn't a universal standard of how to access data out of a JSON object.
Every framework I use seems to slice the problem in a different way.

Have you used json pointers? I've used them in a recent project and they seem nifty. They also handle the issue of "what happens if the meta characters are part of my key" by being able to encode the special characters used.

2017-02-15 23:35 UTC, tannerlinsley commented
Interesting.  Yeah at this point, I think some documentation and a workaround might be helpful in the docs.  In fact, if you want to switch this PR to that, I would accept it in a heartbeat :)

2017-02-16 00:32 UTC, avnunn commented
I've updated my commit to add some documentation about accessors.
It makes sense to me, but I also read the code to see how it works, but its still more information currently available.

Feel free to copy and make any changes you'd like.

2017-02-16 00:38 UTC, tannerlinsley commented
Very nice!  I'll merge and add some edits changes with the next release. Thanks man!

2017-02-16 00:39 UTC, merged